//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCSSBorderPlugin\src\main\java\com\ashera\layout\decorator\Border.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Border")
#ifdef RESTRICT_Border
#define INCLUDE_ALL_Border 0
#else
#define INCLUDE_ALL_Border 1
#endif
#undef RESTRICT_Border

#if !defined (ASBorder_) && (INCLUDE_ALL_Border || defined(INCLUDE_ASBorder))
#define ASBorder_

@class JavaLangFloat;
@class JavaLangInteger;
@class NSString;

@interface ASBorder : NSObject

#pragma mark Public

- (instancetype)init;

- (float)getBottomLeftRadius;

- (float)getBottomRightRadius;

- (id)getColor;

- (int32_t)getDashSpacing;

- (int32_t)getDashWidth;

- (NSString *)getStyle;

- (float)getTopLeftRadius;

- (float)getTopRightRadius;

- (int32_t)getWidth;

- (void)setBottomLeftRadiusWithFloat:(float)bottomLeftRadius;

- (void)setBottomRightRadiusWithFloat:(float)bottomRightRadius;

- (void)setColorWithId:(id)color;

- (void)setDashSpacingWithInt:(int32_t)dashSpacing;

- (void)setDashWidthWithInt:(int32_t)dashWidth;

- (void)setStyleWithNSString:(NSString *)style;

- (void)setTopLeftRadiusWithFloat:(float)topLeftRadius;

- (void)setTopRightRadiusWithFloat:(float)topRightRadius;

- (void)setWidthWithInt:(int32_t)width;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBorder)

FOUNDATION_EXPORT void ASBorder_init(ASBorder *self);

FOUNDATION_EXPORT ASBorder *new_ASBorder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBorder *create_ASBorder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASBorder)

@compatibility_alias ComAsheraLayoutDecoratorBorder ASBorder;


#endif

#pragma pop_macro("INCLUDE_ALL_Border")
