//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCSSBorderPlugin\src\main\java\com\ashera\cssborder\BorderViewImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BorderViewImpl")
#ifdef RESTRICT_BorderViewImpl
#define INCLUDE_ALL_BorderViewImpl 0
#else
#define INCLUDE_ALL_BorderViewImpl 1
#endif
#undef RESTRICT_BorderViewImpl

#if !defined (ASBorderViewImpl_) && (INCLUDE_ALL_BorderViewImpl || defined(INCLUDE_ASBorderViewImpl))
#define ASBorderViewImpl_

#define RESTRICT_IAttributable 1
#define INCLUDE_ASIAttributable 1
#include "IAttributable.h"

@class ASWidgetAttribute;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;

@interface ASBorderViewImpl : NSObject < ASIAttributable >

#pragma mark Public

- (instancetype)init;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (NSString *)getLocalName;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIAttributable>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBorderViewImpl)

inline NSString *ASBorderViewImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASBorderViewImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASBorderViewImpl, LOCAL_NAME, NSString *)

FOUNDATION_EXPORT void ASBorderViewImpl_init(ASBorderViewImpl *self);

FOUNDATION_EXPORT ASBorderViewImpl *new_ASBorderViewImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBorderViewImpl *create_ASBorderViewImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASBorderViewImpl)

@compatibility_alias ComAsheraCssborderBorderViewImpl ASBorderViewImpl;

#endif

#pragma pop_macro("INCLUDE_ALL_BorderViewImpl")
