//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSCSSBorderPlugin\src\main\java\com\ashera\layout\decorator\BorderDecorator.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_BorderDecorator")
#ifdef RESTRICT_BorderDecorator
#define INCLUDE_ALL_BorderDecorator 0
#else
#define INCLUDE_ALL_BorderDecorator 1
#endif
#undef RESTRICT_BorderDecorator

#if !defined (ASBorderDecorator_) && (INCLUDE_ALL_BorderDecorator || defined(INCLUDE_ASBorderDecorator))
#define ASBorderDecorator_

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

@class ASBorder;
@class ASWidgetAttribute;
@class IOSObjectArray;
@class JavaLangFloat;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASBorderDecorator : NSObject < ASILifeCycleDecorator > {
 @public
  id defaultColor_;
}

#pragma mark Public

- (instancetype)init;

- (void)createBorderWithFloat:(float)x1
                    withFloat:(float)y1
                    withFloat:(float)x2
                    withFloat:(float)y2
                       withId:(id)canvas
                       withId:(id)path
                       withId:(id)paint
                 withASBorder:(ASBorder *)border
                 withNSString:(NSString *)where;

- (void)createBorderColorWithId:(id)color;

- (void)createBorderColorBottomWithId:(id)color;

- (void)createBorderColorLeftWithId:(id)color;

- (void)createBorderColorRightWithId:(id)color;

- (void)createBorderColorTopWithId:(id)color;

- (void)createBorderDashSpacingWithInt:(int32_t)dashSpacing;

- (void)createBorderDashSpacingBottomWithInt:(int32_t)dashSpacing;

- (void)createBorderDashSpacingLeftWithInt:(int32_t)dashSpacing;

- (void)createBorderDashSpacingRightWithInt:(int32_t)dashSpacing;

- (void)createBorderDashSpacingTopWithInt:(int32_t)dashSpacing;

- (void)createBorderDashWidthWithInt:(int32_t)dashWidth;

- (void)createBorderDashWidthBottomWithInt:(int32_t)dashWidth;

- (void)createBorderDashWidthLeftWithInt:(int32_t)dashWidth;

- (void)createBorderDashWidthRightWithInt:(int32_t)dashWidth;

- (void)createBorderDashWidthTopWithInt:(int32_t)dashWidth;

- (void)createBorderRadiusWithFloat:(float)radius;

- (void)createBorderRadiusBottomLeftWithFloat:(float)radius;

- (void)createBorderRadiusBottomRightWithFloat:(float)radius;

- (void)createBorderRadiusTopLeftWithFloat:(float)radius;

- (void)createBorderRadiusTopRightWithFloat:(float)radius;

- (void)createBorderStyleWithNSString:(NSString *)style;

- (void)createBorderStyleBottomWithNSString:(NSString *)style;

- (void)createBorderStyleLeftWithNSString:(NSString *)style;

- (void)createBorderStyleRightWithNSString:(NSString *)style;

- (void)createBorderStyleTopWithNSString:(NSString *)style;

- (void)createBorderWidthWithInt:(int32_t)borderWith;

- (void)createBorderWidthBottomWithInt:(int32_t)borderWith;

- (void)createBorderWidthLeftWithInt:(int32_t)borderWith;

- (void)createBorderWidthRightWithInt:(int32_t)borderWith;

- (void)createBorderWidthTopWithInt:(int32_t)borderWith;

- (void)createMask;

- (void)drawableStateChanged;

- (void)drawRectWithId:(id)cgRect;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)args;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)nativeCreateBorderBottomWithASBorder:(ASBorder *)borderBottom
                                      withId:(id)wrapperRect;

- (void)nativeCreateBorderLeftWithASBorder:(ASBorder *)borderLeft
                                    withId:(id)wrapperRect;

- (void)nativeCreateBorderRightWithASBorder:(ASBorder *)borderRight
                                     withId:(id)wrapperRect;

- (void)nativeCreateBorderTopWithASBorder:(ASBorder *)borderTop
                                   withId:(id)wrapperRect;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

@end

J2OBJC_STATIC_INIT(ASBorderDecorator)

J2OBJC_FIELD_SETTER(ASBorderDecorator, defaultColor_, id)

FOUNDATION_EXPORT void ASBorderDecorator_init(ASBorderDecorator *self);

FOUNDATION_EXPORT ASBorderDecorator *new_ASBorderDecorator_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBorderDecorator *create_ASBorderDecorator_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASBorderDecorator)

@compatibility_alias ComAsheraLayoutDecoratorBorderDecorator ASBorderDecorator;


#endif

#if !defined (ASBorderDecorator_Arc_) && (INCLUDE_ALL_BorderDecorator || defined(INCLUDE_ASBorderDecorator_Arc))
#define ASBorderDecorator_Arc_

@class JavaLangFloat;
@class JavaLangInteger;

@interface ASBorderDecorator_Arc : NSObject {
 @public
  float left_;
  float top_;
  float right_;
  float bottom_;
  int32_t startAngle_;
  int32_t sweepAngle_;
}

#pragma mark Public

- (instancetype)initWithFloat:(float)left
                    withFloat:(float)top
                    withFloat:(float)right
                    withFloat:(float)bottom
                      withInt:(int32_t)startAngle
                      withInt:(int32_t)sweepAngle;

- (int32_t)getEndAngle;

- (float)getHeight;

- (float)getMidPointX;

- (float)getMidPointY;

- (float)getRadius;

- (int32_t)getStartAngle;

- (float)getWidth;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASBorderDecorator_Arc)

FOUNDATION_EXPORT void ASBorderDecorator_Arc_initWithFloat_withFloat_withFloat_withFloat_withInt_withInt_(ASBorderDecorator_Arc *self, float left, float top, float right, float bottom, int32_t startAngle, int32_t sweepAngle);

FOUNDATION_EXPORT ASBorderDecorator_Arc *new_ASBorderDecorator_Arc_initWithFloat_withFloat_withFloat_withFloat_withInt_withInt_(float left, float top, float right, float bottom, int32_t startAngle, int32_t sweepAngle) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASBorderDecorator_Arc *create_ASBorderDecorator_Arc_initWithFloat_withFloat_withFloat_withFloat_withInt_withInt_(float left, float top, float right, float bottom, int32_t startAngle, int32_t sweepAngle);

J2OBJC_TYPE_LITERAL_HEADER(ASBorderDecorator_Arc)


#endif

#pragma pop_macro("INCLUDE_ALL_BorderDecorator")
